<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\BASE.Service.Core.BL\BASE.Service.Core.BL.csproj" />
    <ProjectReference Include="..\..\DL\EasyMart.DLBase\EasyMart.DLBase.csproj" />
    <ProjectReference Include="..\..\Model\EasyMart.Model\EasyMart.Model.csproj" />
  </ItemGroup>

</Project>
