<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.3.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\DL\EasyMart.DL\EasyMart.DL.csproj" />
    <ProjectReference Include="..\EasyMart.BLBase\EasyMart.BLBase.csproj" />
  </ItemGroup>

</Project>
